export const projectsData = [
  {
    id: 1,
    title: 'My portfolio',
    description: 'The portfolio♥! Showing some of my awesome projects.',
    tags: ['HTML', 'CSS', 'Tailwindcss', 'JavaScript', 'React'],
    image: '/assets/portfolio.png',
    code: 'https://github.com/Isaacvf-dev/portfolio',
    live: 'https://isaac-vieira.netlify.app/',
  },
  {
    id: 2,
    title: 'DripBR Barbershop',
    description: 'Landing Page for Barbershop client',
    tags: ['HTML', 'CSS', 'Tailwindcss', 'JavaScript', 'Vue', 'Nuxt'],
    image: '/assets/dripbr.png',
    code: 'https://github.com/lostcode-js/lp-drip-barber',
    live: 'https://www.dripbr.com/',
  },
  {
    id: 3,
    title: 'Marvel Webpage',
    description: "Landing Page consuming Marvel’s API",
    tags: ['HTML', 'CSS', 'Bootstrap', 'JavaScript', 'Vue'],
    image: '/assets/marvel.png',
    code: 'https://github.com/Isaacvf-dev/lp-Marvel',
    live: 'https://marvel-the-api.netlify.app/',
  },
  {
    id: 4,
    title: 'Jambu',
    description: 'SEO-focused Landing Page for a Restaurant and first time using Nuxt.',
    tags: ['HTML', 'CSS', 'Tailwindcss', 'JavaScript', 'Vue', 'Nuxt'],
    image: '/assets/jambu.png',
    code: 'https://github.com/lostcode-js/lp-jambu-bar',
    live: 'https://lp-jambu-bar.vercel.app/',
  },
  {
    id: 5,
    title: 'Quizzical',
    description: 'Reactjs practice, quizz app consuming OTDB API',
    tags: ['HTML', 'CSS', 'JavaScript', 'React'],
    image: '/assets/quizzical.png',
    code: 'https://github.com/Isaacvf-dev/Quizzical-App',
    live: 'https://quizzik.netlify.app/',
  },
  {
    id: 6,
    title: 'Notes',
    description: 'Landing page for a fictional cafe with various features and responsive design.',
    tags: ['HTML', 'CSS', 'JavaScript', 'React'],
    image: '/assets/notes.png',
    code: 'https://github.com/Isaacvf-dev/Notes-app',
    live: 'https://notesappy.netlify.app/',
  },
]